import fs from "node:fs";
import path from "node:path";
import { opsErrorResult, textResult, gdEscape, ensureDir, writeAtomic } from "../util.js";
import { requireProjectPath, resolveWithinRoot, normalizeUserProjectPath } from "../path-utils.js";
import { resolveGodotPath, spawnGodot } from "../godot-process.js";
import { executeGdscript, parseGdscriptResult, SCENE_TREE_HEADER } from "../gdscript.js";

// ─── dev_loop: session state file memory ─────────────────────────────────────

export function formatSessionState(state) {
  const lines = ["# Session State", "", "> Auto-generated by dev_loop save_state", "", "## Current Task", "", state.current_task, ""];
  if (state.epic || state.feature) {
    lines.push("## Context", "");
    if (state.epic) lines.push(`- **Epic**: ${state.epic}`);
    if (state.feature) lines.push(`- **Feature**: ${state.feature}`);
    lines.push("");
  }
  if (state.files_modified?.length) {
    lines.push("## Files Modified", "");
    for (const f of state.files_modified) lines.push(`- \`${f}\``);
    lines.push("");
  }
  if (state.decisions?.length) {
    lines.push("## Key Decisions", "");
    for (const d of state.decisions) lines.push(`- ${d}`);
    lines.push("");
  }
  if (state.open_questions?.length) {
    lines.push("## Open Questions", "");
    for (const q of state.open_questions) lines.push(`- [ ] ${q}`);
    lines.push("");
  }
  return lines.join("\n");
}

// ─── scene_snapshot ──────────────────────────────────────────────────────────

export function genSceneSnapshotScript(resPath, maxDepth) {
  return `${SCENE_TREE_HEADER}
func _initialize():
\tvar packed := load("${gdEscape(resPath)}")
\tif packed == null:
\t\t_mcp_output("error", "Failed to load scene: ${gdEscape(resPath)}")
\t\t_mcp_done()
\t\treturn
\tvar instance: Node = packed.instantiate()
\tvar _root: Node = _mcp_get_root()
\tif _root == null:
\t\t_mcp_output("error", "Scene root not available")
\t\tinstance.queue_free()
\t\t_mcp_done()
\t\treturn
\t_root.add_child(instance)
\tvar data := _snap(instance, ${maxDepth}, 0)
\t_mcp_output("snapshot", data)
\tinstance.queue_free()
\t_mcp_done()

func _snap(node: Node, max_depth: int, depth: int) -> Dictionary:
\tvar info := {"name": node.name, "type": node.get_class()}
\tif node is Node2D:
\t\tinfo["position"] = {"x": node.position.x, "y": node.position.y}
\t\tinfo["rotation"] = node.rotation
\tif node is Node3D:
\t\tinfo["position"] = {"x": node.position.x, "y": node.position.y, "z": node.position.z}
\tif depth < max_depth:
\t\tvar ch: Array = []
\t\tfor c in node.get_children():
\t\t\tch.append(_snap(c, max_depth, depth + 1))
\t\tinfo["child_count"] = ch.size()
\t\tinfo["children"] = ch
\treturn info
`;
}

export function flattenSnapshot(node, prefix = "") {
  const pathStr = prefix ? `${prefix}/${node.name}` : String(node.name);
  const rows = [{ path: pathStr, type: node.type }];
  if (Array.isArray(node.children)) {
    for (const c of node.children) rows.push(...flattenSnapshot(c, pathStr));
  }
  return rows;
}

export function diffSnapshots(before, after) {
  const beforeMap = new Map(flattenSnapshot(before).map((r) => [r.path, r.type]));
  const afterMap = new Map(flattenSnapshot(after).map((r) => [r.path, r.type]));
  const added = [];
  const removed = [];
  const type_changed = [];
  for (const [p, t] of afterMap) {
    if (!beforeMap.has(p)) added.push(p);
    else if (beforeMap.get(p) !== t) type_changed.push({ path: p, before: beforeMap.get(p), after: t });
  }
  for (const [p] of beforeMap) {
    if (!afterMap.has(p)) removed.push(p);
  }
  return { added, removed, type_changed, unchanged: [...afterMap.keys()].filter((p) => beforeMap.get(p) === afterMap.get(p)).length };
}

// ─── GDD validator (8-section standard) ──────────────────────────────────────

export const GDD_REQUIRED_SECTIONS = [
  "Overview", "Player Fantasy", "Detailed Rules", "Formulas",
  "Edge Cases", "Dependencies", "Tuning Knobs", "Acceptance Criteria",
];

export const GDD_SECTION_HINTS = {
  Overview: "Describe the system's purpose, scope, and how it fits into the larger game.",
  "Player Fantasy": "What experience does this system deliver to the player? How should it feel?",
  "Detailed Rules": "Enumerate every rule the system follows. Be explicit and unambiguous.",
  Formulas: "Define all math using named variables (e.g., damage = base_damage * multiplier), not raw numbers.",
  "Edge Cases": "List boundary conditions: min/max values, ties, empty states, overflow, etc.",
  Dependencies: "List other systems this one reads from or writes to. Use bullet format. Write 'None' if standalone.",
  "Tuning Knobs": "Identify every configurable parameter with its current default, range, and effect.",
  "Acceptance Criteria": "Write testable bullet items (- or *) that a QA engineer can verify. Each must be pass/fail.",
};

const MIN_SECTION_BODY_LENGTH = 20;

function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function extractSectionBody(markdown, sectionName) {
  const headerRegex = new RegExp(`^##\\s+${escapeRegex(sectionName)}\\s*$`, "m");
  const match = headerRegex.exec(markdown);
  if (!match) return "";
  const start = match.index + match[0].length;
  const rest = markdown.slice(start);
  const nextHeader = rest.search(/^## /m);
  return (nextHeader === -1 ? rest : rest.slice(0, nextHeader)).trim();
}

function findHardcodedNumbers(body) {
  const regex = /(?<![a-zA-Z_])\b\d+(?:\.\d+)?\b/g;
  const results = [];
  let m;
  while ((m = regex.exec(body)) !== null) results.push(parseFloat(m[0]));
  return results;
}

function hasBulletItems(text) {
  return /^\s*[-*]\s+/m.test(text);
}

export function validateGDD(markdown) {
  const issues = [];
  const sections_found = [];
  const sections_missing = [];

  for (const section of GDD_REQUIRED_SECTIONS) {
    const headerRegex = new RegExp(`^##\\s+${escapeRegex(section)}\\s*$`, "m");
    if (headerRegex.test(markdown)) {
      sections_found.push(section);
    } else {
      sections_missing.push(section);
      issues.push({
        severity: "error",
        location: section,
        message: `Missing required section: ${section}`,
        suggestion: GDD_SECTION_HINTS[section],
      });
    }
  }

  for (const section of sections_found) {
    const body = extractSectionBody(markdown, section);
    if (body.length < MIN_SECTION_BODY_LENGTH) {
      issues.push({
        severity: "warning",
        location: section,
        message: `Section body is too short (${body.length} chars, minimum ${MIN_SECTION_BODY_LENGTH})`,
        suggestion: `Expand the ${section} section. ${GDD_SECTION_HINTS[section]}`,
      });
    }
  }

  if (sections_found.includes("Formulas")) {
    const body = extractSectionBody(markdown, "Formulas");
    if (body.length > 0) {
      const numbers = findHardcodedNumbers(body);
      if (numbers.length > 0) {
        issues.push({
          severity: "warning",
          location: "Formulas",
          message: `Hardcoded numbers found: ${numbers.join(", ")}`,
          suggestion: "Replace raw numbers with named tuning variables (e.g., base_damage, multiplier).",
        });
      }
    }
  }

  if (sections_found.includes("Acceptance Criteria")) {
    const body = extractSectionBody(markdown, "Acceptance Criteria");
    if (body.length > 0 && !hasBulletItems(body)) {
      issues.push({
        severity: "warning",
        location: "Acceptance Criteria",
        message: "Acceptance Criteria should use bullet list items (- or *) for testable checks",
        suggestion: "Rewrite as a bullet list, e.g.:\n- [ ] When player deals damage, health decreases by the expected amount",
      });
    }
  }

  if (sections_found.includes("Dependencies")) {
    const body = extractSectionBody(markdown, "Dependencies");
    if (body.length > 0 && body.toLowerCase() !== "none" && !hasBulletItems(body)) {
      issues.push({
        severity: "warning",
        location: "Dependencies",
        message: "Dependencies section should use bullet list format or state 'None'",
        suggestion: "List dependencies as bullet items, e.g.:\n- Combat system (reads player stats)\n- UI system (displays health bar)",
      });
    }
  }

  const passed = sections_missing.length === 0 && !issues.some((i) => i.severity === "error");
  return { passed, sections_found, sections_missing, issues };
}

// ─── Chain-of-Verification ───────────────────────────────────────────────────

const COV_QUESTION_TEMPLATES = [
  "What if the analysis {reason} — could the verdict '{verdict}' be based on incomplete context from '{context}'?",
  "Could there be hidden assumptions in the verdict '{verdict}' that might not hold given the context '{context}'?",
  "Might this verdict overlook edge cases or boundary conditions that '{context}' does not explicitly address?",
  "Is it possible that '{context}' contains misleading signals that led to the verdict '{verdict}'?",
  "What if the evidence in '{context}' is wrong or outdated — would the verdict '{verdict}' still be valid?",
];

const WEAK_SIGNALS_CONTEXT = ["skipped", "only checked", "partial"];
const WEAK_SIGNALS_VERDICT = ["concerns", "fail"];

export function chainOfVerification(verdict, context) {
  const reason = "missed critical interactions between subsystems";
  const questions = COV_QUESTION_TEMPLATES.map((tpl) =>
    tpl.replace(/\{verdict\}/g, verdict).replace(/\{context\}/g, context).replace(/\{reason\}/g, reason));

  let confidence = 0.9;
  const contextLower = context.toLowerCase();
  const verdictLower = verdict.toLowerCase();
  for (const signal of WEAK_SIGNALS_CONTEXT) if (contextLower.includes(signal)) confidence -= 0.15;
  for (const signal of WEAK_SIGNALS_VERDICT) if (verdictLower.includes(signal)) confidence -= 0.15;
  if (context.length < 30) confidence -= 0.15;
  confidence = Math.max(0.1, Math.min(1.0, confidence));

  let recommendation;
  if (confidence < 0.7) recommendation = "Low confidence — recommend manual review before proceeding";
  else if (confidence < 0.9) recommendation = "Moderate confidence — verify key concerns manually";
  else recommendation = "High confidence — verdict is well-supported by evidence";

  return { original_verdict: verdict, questions, confidence, recommendation };
}

// ─── Code templates (core set ported from upstream code-templates) ───────────
// Ported: 4 of upstream's 11 built-in code templates (T001, T002, T008, T010).
// Architecture/scaffold/user-template sets are deferred.

export const TEMPLATES = [
  {
    id: "T001",
    name: "camera3d_setup",
    description: "Camera3D + look_at, add_child before look_at",
    params: [
      { name: "position", type: "Vector3", default: "Vector3(0, 5, 10)" },
      { name: "target", type: "Vector3", default: "Vector3.ZERO" },
    ],
    generate: (p) => `var cam := Camera3D.new()
cam.position = ${p.position ?? "Vector3(0, 5, 10)"}
add_child(cam)
cam.look_at(${p.target ?? "Vector3.ZERO"})`,
  },
  {
    id: "T002",
    name: "rigidbody3d_with_bounce",
    description: "RigidBody3D + PhysicsMaterial + CollisionShape3D",
    params: [
      { name: "position", type: "Vector3", default: "Vector3.ZERO" },
      { name: "radius", type: "float", default: "0.5" },
      { name: "bounce", type: "float", default: "0.4" },
      { name: "mass", type: "float", default: "1.0" },
    ],
    generate: (p) => `var rb := RigidBody3D.new()
rb.position = ${p.position ?? "Vector3.ZERO"}
rb.mass = ${p.mass ?? "1.0"}
var phys_mat := PhysicsMaterial.new()
phys_mat.bounce = ${p.bounce ?? "0.4"}
rb.physics_material_override = phys_mat
var mesh_inst := MeshInstance3D.new()
var sphere := SphereMesh.new()
sphere.radius = ${p.radius ?? "0.5"}
mesh_inst.mesh = sphere
rb.add_child(mesh_inst)
var col := CollisionShape3D.new()
var shape := SphereShape3D.new()
shape.radius = ${p.radius ?? "0.5"}
col.shape = shape
rb.add_child(col)
add_child(rb)`,
  },
  {
    id: "T008",
    name: "character_body_2d_movement",
    description: "CharacterBody2D move_and_slide() + input handling",
    params: [
      { name: "speed", type: "float", default: "300.0" },
      { name: "jump_velocity", type: "float", default: "-400.0" },
    ],
    generate: (p) => `extends CharacterBody2D

const SPEED = ${p.speed ?? "300.0"}
const JUMP_VELOCITY = ${p.jump_velocity ?? "-400.0"}

var gravity: float = ProjectSettings.get_setting("physics/2d/default_gravity")

func _physics_process(delta):
\tif not is_on_floor():
\t\tvelocity.y += gravity * delta

\tif Input.is_action_just_pressed("ui_accept") and is_on_floor():
\t\tvelocity.y = JUMP_VELOCITY

\tvar direction = Input.get_axis("ui_left", "ui_right")
\tif direction:
\t\tvelocity.x = direction * SPEED
\telse:
\t\tvelocity.x = move_toward(velocity.x, 0, SPEED)

\tmove_and_slide()`,
  },
  {
    id: "T010",
    name: "state_machine_simple",
    description: "Simple enum + match state management",
    params: [{ name: "states", type: "string", default: "IDLE,RUN,JUMP" }],
    generate: (p) => {
      const stateNames = (p.states ?? "IDLE,RUN,JUMP").split(",");
      const enumBody = stateNames.map((s) => `\t${s.trim()}`).join(",\n");
      const matchBody = stateNames.map((s) => `\t\t${s.trim()}:\n\t\t\tpass`).join("\n");
      return `enum State {
${enumBody}
}

var current_state: State = State.${stateNames[0].trim()}

func _process(delta):
\tmatch current_state:
${matchBody}

func transition_to(new_state: State):
\tcurrent_state = new_state`;
    },
  },
];

function sanitizeTemplateValue(value) {
  if (!/^[A-Za-z0-9_."() \t,\-+*/%:!<>#]+$/.test(value)) {
    throw new Error(`Template variable value contains disallowed characters: "${String(value).slice(0, 50)}"`);
  }
  return value;
}

// ─── Tool definitions ────────────────────────────────────────────────────────

export const tools = [
  {
    name: "dev_loop",
    description: "Development loop: execute GDScript headlessly, optionally verify the project loads cleanly (-e --quit), and capture outputs. save_state writes a markdown session-state file under the harness traceDir (file-as-memory).",
    inputSchema: {
      type: "object",
      properties: {
        project_path: { type: "string", description: "Path to the Godot project directory" },
        code: { type: "string", description: "GDScript code to execute (snippet or full extends SceneTree)" },
        verify: { type: "boolean", description: "Also verify the project loads cleanly after execution (default false)", default: false },
        timeout: { type: "number", description: "Timeout per step in seconds (default 30)", default: 30 },
        save_state: {
          type: "object",
          description: "Save session state to a markdown file under traceDir/dev-loop-state/",
          properties: {
            file_name: { type: "string", description: "File name (default active.md, *.md only, no directories)" },
            task: { type: "string", description: "Current task description" },
            epic: { type: "string" },
            feature: { type: "string" },
            files_modified: { type: "array", items: { type: "string" } },
            decisions: { type: "array", items: { type: "string" } },
            open_questions: { type: "array", items: { type: "string" } },
          },
        },
        godot_path: { type: "string", description: "Optional explicit path to the Godot binary" },
      },
      required: ["project_path", "code"],
    },
  },
  {
    name: "scene_snapshot",
    description: "Capture a structured scene tree snapshot (name/type/position, up to max_depth). Pass an optional previous snapshot in `before` to get an added/removed/type-changed comparison.",
    inputSchema: {
      type: "object",
      properties: {
        project_path: { type: "string", description: "Path to the Godot project directory" },
        scene_path: { type: "string", description: "Scene file path relative to project (or res:// path)" },
        max_depth: { type: "number", description: "Max tree depth (default 5)", default: 5 },
        before: { type: "object", description: "Optional previous snapshot object for before/after comparison" },
        godot_path: { type: "string", description: "Optional explicit path to the Godot binary" },
      },
      required: ["project_path", "scene_path"],
    },
  },
  {
    name: "batch_validate",
    description: "Validate multiple GDScript files headlessly in one call (parse check per file, --check-only).",
    inputSchema: {
      type: "object",
      properties: {
        project_path: { type: "string", description: "Path to the Godot project directory" },
        scripts: { type: "array", items: { type: "string" }, description: "Script paths relative to project (or res:// paths)" },
        timeout: { type: "number", description: "Per-file timeout in seconds (default 15)", default: 15 },
        godot_path: { type: "string", description: "Optional explicit path to the Godot binary" },
      },
      required: ["project_path", "scripts"],
    },
  },
  {
    name: "validate_gdd",
    description: "Validate a Game Design Document markdown file against the 8-section standard (Overview, Player Fantasy, Detailed Rules, Formulas, Edge Cases, Dependencies, Tuning Knobs, Acceptance Criteria). Pure file analysis, no Godot process.",
    inputSchema: {
      type: "object",
      properties: {
        project_path: { type: "string", description: "Path to the Godot project directory" },
        gdd_path: { type: "string", description: "GDD markdown file path relative to project root" },
      },
      required: ["project_path", "gdd_path"],
    },
  },
  {
    name: "chain_verify",
    description: "Run a Chain-of-Verification self-challenge on a review conclusion: generates 5 challenge questions, scores confidence, and recommends next steps. Pure logic, no Godot process.",
    inputSchema: {
      type: "object",
      properties: {
        verdict: { type: "string", description: "The verdict or conclusion to challenge" },
        context: { type: "string", description: "The supporting context or evidence for the verdict" },
      },
      required: ["verdict", "context"],
    },
  },
  {
    name: "list_templates",
    description: "List built-in GDScript code templates (core set of 4 ported from upstream: T001, T002, T008, T010). Pure JS, no Godot process.",
    inputSchema: {
      type: "object",
      properties: {
        tag: { type: "string", description: "Optional filter: substring match on name/description" },
      },
    },
  },
  {
    name: "apply_template",
    description: "Apply a built-in code template to a script path in the project (writes the generated GDScript to disk).",
    inputSchema: {
      type: "object",
      properties: {
        project_path: { type: "string", description: "Path to the Godot project directory" },
        template_id: { type: "string", description: "Template ID (e.g. T008)" },
        script_path: { type: "string", description: "Target script path relative to project (e.g. scripts/player.gd)" },
        variables: { type: "object", description: "Template variable overrides (key/value)" },
      },
      required: ["project_path", "template_id", "script_path"],
    },
  },
];

// ─── Handler ─────────────────────────────────────────────────────────────────

export async function handle(toolName, args, ctx) {
  try {
    switch (toolName) {
      case "dev_loop": {
        const projectPath = requireProjectPath(args);
        const code = args.code;
        if (typeof code !== "string" || code.trim() === "") {
          return opsErrorResult("INVALID_PARAMS", '"code" must be a non-empty string.');
        }
        const verify = args.verify === true;
        const timeout = Math.min(Math.max(Math.round(Number(args.timeout) || 30), 5), 120);
        const godot = await resolveGodotPath(args.godot_path ?? ctx.godotPath);

        const execResult = await executeGdscript({ godotPath: godot, projectPath, code, timeout });
        const result = { step1_execute: execResult.compile_success ? "success" : "compile_error" };

        if (!execResult.compile_success) {
          result.compile_error = execResult.compile_error;
          return textResult(JSON.stringify(result, null, 2));
        }
        if (!execResult.run_success) {
          result.step1_execute = "runtime_error";
          result.run_error = execResult.run_error;
          return textResult(JSON.stringify(result, null, 2));
        }

        const outputs = {};
        for (const entry of execResult.outputs) {
          try { outputs[entry.key] = JSON.parse(entry.value); } catch { outputs[entry.key] = entry.value; }
        }
        result.outputs = outputs;

        if (verify) {
          const v = await spawnGodot(godot, ["--headless", "--path", projectPath, "-e", "--quit"], { timeoutMs: 20000 });
          if (v.timedOut) {
            result.step2_verify = { status: "timeout", output: v.stdout.slice(-2000) };
          } else {
            const combined = `${v.stdout}\n${v.stderr}`;
            const errorLines = combined.split("\n").filter((l) => l.includes("SCRIPT ERROR") || l.includes("Parse Error"));
            result.step2_verify = errorLines.length > 0
              ? { status: "error", errors: errorLines.slice(0, 10) }
              : { status: "ok" };
          }
        }

        if (args.save_state && typeof args.save_state === "object" && !Array.isArray(args.save_state)) {
          const ss = args.save_state;
          let fileName = typeof ss.file_name === "string" && ss.file_name ? ss.file_name : "active.md";
          if (!/^[\w-]+\.md$/.test(fileName)) {
            return opsErrorResult("INVALID_PARAMS", 'save_state.file_name must match *.md with no directories (letters/digits/_/-)');
          }
          const stateDir = path.join(ctx.traceDir, "dev-loop-state");
          fs.mkdirSync(stateDir, { recursive: true });
          const fullPath = path.join(stateDir, fileName);
          const content = formatSessionState({
            current_task: ss.task || "Unknown task",
            epic: ss.epic,
            feature: ss.feature,
            files_modified: ss.files_modified,
            decisions: ss.decisions,
            open_questions: ss.open_questions,
          });
          writeAtomic(fullPath, content);
          result.save_state = { saved: true, path: fullPath };
        }

        return textResult(JSON.stringify(result, null, 2));
      }

      case "scene_snapshot": {
        const projectPath = requireProjectPath(args);
        const scenePath = args.scene_path;
        if (!scenePath) return opsErrorResult("INVALID_PARAMS", '"scene_path" is required for scene_snapshot.');
        const rel = normalizeUserProjectPath(String(scenePath));
        try { resolveWithinRoot(projectPath, rel); } catch {
          return opsErrorResult("INVALID_PATH", "scene_path contains path traversal");
        }
        const maxDepth = Math.min(Math.max(Math.floor(Number(args.max_depth) || 5), 1), 20);
        const resPath = rel.startsWith("res://") ? rel : `res://${rel.replace(/\\/g, "/")}`;
        const godot = await resolveGodotPath(args.godot_path ?? ctx.godotPath);
        const execResult = await executeGdscript({ godotPath: godot, projectPath, code: genSceneSnapshotScript(resPath, maxDepth), timeout: 30, trusted: true });
        const parsed = parseGdscriptResult(execResult, { mapError: () => "SNAPSHOT_FAILED" });
        if (parsed.isError) return parsed;
        const payload = JSON.parse(parsed.content[0].text);
        let snapshot = payload.snapshot;
        if (typeof snapshot === "string") {
          try { snapshot = JSON.parse(snapshot); } catch { /* keep string */ }
        }
        const out = { success: true, snapshot };
        if (args.before && typeof args.before === "object" && snapshot && typeof snapshot === "object") {
          out.comparison = diffSnapshots(args.before, snapshot);
        }
        return textResult(JSON.stringify(out, null, 2));
      }

      case "batch_validate": {
        const projectPath = requireProjectPath(args);
        const scripts = args.scripts;
        if (!Array.isArray(scripts) || scripts.length === 0) {
          return opsErrorResult("INVALID_PARAMS", '"scripts" must be a non-empty array of file paths.');
        }
        if (scripts.length > 50) {
          return opsErrorResult("INVALID_PARAMS", `Too many scripts (${scripts.length}). Maximum: 50`);
        }
        const godot = await resolveGodotPath(args.godot_path ?? ctx.godotPath);
        const perFileTimeout = Math.min(Math.max(Math.round(Number(args.timeout) || 15), 5), 60);

        const results = {};
        let allValid = true;
        for (const s of scripts) {
          const rel = normalizeUserProjectPath(String(s));
          let abs;
          try { abs = resolveWithinRoot(projectPath, rel); } catch {
            results[s] = { valid: false, error: "Path traversal" };
            allValid = false;
            continue;
          }
          if (!fs.existsSync(abs)) {
            results[s] = { valid: false, error: "File not found" };
            allValid = false;
            continue;
          }
          const res = await spawnGodot(godot, ["--headless", "--path", projectPath, "--check-only", "--script", abs], { timeoutMs: perFileTimeout * 1000 });
          const combined = `${res.stdout}\n${res.stderr}`;
          const errorLines = combined.split("\n").filter((l) => l.includes("SCRIPT ERROR") || l.includes("Parse Error"));
          if (res.timedOut) {
            results[s] = { valid: false, error: "Validation timed out" };
            allValid = false;
          } else if (errorLines.length > 0) {
            results[s] = { valid: false, error: errorLines.map((l) => l.trim()).slice(0, 5) };
            allValid = false;
          } else {
            results[s] = { valid: true };
          }
        }
        return textResult(JSON.stringify({ all_valid: allValid, total: scripts.length, results }, null, 2));
      }

      case "validate_gdd": {
        const projectPath = requireProjectPath(args);
        const gddPath = args.gdd_path;
        if (!gddPath || typeof gddPath !== "string") {
          return opsErrorResult("INVALID_PARAMS", "gdd_path is required");
        }
        let fullPath;
        try { fullPath = resolveWithinRoot(projectPath, gddPath); } catch {
          return opsErrorResult("INVALID_PATH", "gdd_path contains path traversal");
        }
        if (!fs.existsSync(fullPath)) {
          return opsErrorResult("FILE_NOT_FOUND", `GDD file not found: ${gddPath}`);
        }
        const content = fs.readFileSync(fullPath, "utf8");
        return textResult(JSON.stringify(validateGDD(content), null, 2));
      }

      case "chain_verify": {
        const verdict = String(args.verdict ?? "");
        const context = String(args.context ?? "");
        if (!verdict) return opsErrorResult("INVALID_PARAMS", "verdict is required");
        if (!context) return opsErrorResult("INVALID_PARAMS", "context is required");
        return textResult(JSON.stringify(chainOfVerification(verdict, context), null, 2));
      }

      case "list_templates": {
        const tag = args.tag ? String(args.tag).toLowerCase() : undefined;
        let filtered = TEMPLATES;
        if (tag) {
          filtered = filtered.filter((t) => t.name.toLowerCase().includes(tag) || t.description.toLowerCase().includes(tag));
        }
        const lines = filtered.map((t) => `- **${t.id}**: ${t.name} — ${t.description} (params: ${t.params.map((p) => p.name).join(", ") || "none"})`);
        return textResult(`Available templates (${filtered.length}, core set of 4 ported):\n${lines.join("\n")}`);
      }

      case "apply_template": {
        const projectPath = requireProjectPath(args);
        const templateId = String(args.template_id ?? "");
        const scriptPathRaw = String(args.script_path ?? "");
        if (!templateId) return opsErrorResult("INVALID_PARAMS", "template_id is required");
        if (!scriptPathRaw) return opsErrorResult("INVALID_PARAMS", "script_path is required");
        const template = TEMPLATES.find((t) => t.id === templateId);
        if (!template) {
          return opsErrorResult("TEMPLATE_NOT_FOUND", `Template '${templateId}' not found. Available: ${TEMPLATES.map((t) => t.id).join(", ")}`);
        }
        const rel = normalizeUserProjectPath(scriptPathRaw);
        let fullPath;
        try { fullPath = resolveWithinRoot(projectPath, rel); } catch {
          return opsErrorResult("INVALID_PATH", "script_path contains path traversal");
        }
        const userVars = args.variables && typeof args.variables === "object" ? args.variables : {};
        const variables = {};
        try {
          for (const param of template.params) {
            const raw = String(userVars[param.name] ?? param.default);
            variables[param.name] = sanitizeTemplateValue(raw);
          }
        } catch (err) {
          return opsErrorResult("INVALID_PARAMS", err.message);
        }
        const code = template.generate(variables);
        ensureDir(fullPath);
        writeAtomic(fullPath, code);
        return textResult(`Template '${template.name}' applied to ${rel} (${code.split("\n").length} lines)`);
      }

      default:
        return opsErrorResult("UNKNOWN_TOOL", `No handler for tool: ${toolName}`);
    }
  } catch (err) {
    return opsErrorResult("INVALID_PARAMS", err.message);
  }
}
